#!/bin/bash

# Frontend Voice Pipeline Debug Script
# Traces complete iOS voice flow from speech to backend API call

echo "🔍 Frontend Voice Pipeline Debug"
echo "=================================="

echo ""
echo "📱 This script will help you trace:"
echo "- Voice recognition completion"
echo "- Transcript processing" 
echo "- API request formation"
echo "- Network connectivity"
echo "- Backend response handling"
echo ""

echo "🎯 Step 1: Test Voice Recognition"
echo "Speak into your iOS app now and say: 'test voice debugging'"
echo "Watch for these logs in Xcode console:"
echo "- 🏁 VOICE COMPLETE: finishing successfully with transcript"
echo "- 🎤 VOICE CALLBACK: resuming with transcript"
echo ""

echo "🎯 Step 2: Check Function Entry"
echo "Look for these logs:"
echo "- 🎯 FUNCTION ENTRY: processUserMessage called"
echo "- 🎤 VOICE PIPELINE: processing user message"
echo ""

echo "🌐 Step 3: Check API Request Formation"
echo "Look for these logs:"
echo "- 📤 SENDING TO API: message="
echo "- 🌐 API CALL: /ai/converse"
echo "- 📊 SESSION: new"
echo ""

echo "🔍 Step 4: Common Issues & Solutions"
echo ""
echo "If you see voice recognition but NO function entry:"
echo "❌ Issue: processUserMessage not being called"
echo "🔧 Fix: Check voice state management in HomeViewModel"
echo ""
echo "If you see function entry but NO API call:"
echo "❌ Issue: assistantConversationService.respond not being called"
echo "🔧 Fix: Check API service configuration"
echo ""
echo "If you see API call but NO backend logs:"
echo "❌ Issue: Network connectivity from iOS simulator"
echo "🔧 Fix: Check API base URL in RemoteAuthService.swift"
echo ""

echo "📱 Expected Complete Flow:"
echo "1. 🏁 VOICE COMPLETE: transcript='test voice debugging'"
echo "2. 🎯 FUNCTION ENTRY: processUserMessage called"
echo "3. 🎤 VOICE PIPELINE: processing message='test voice debugging'"
echo "4. 📤 SENDING TO API: message='test voice debugging'"
echo "5. 🌐 API CALL: /ai/converse"
echo "6. 📊 SESSION: new"
echo "7. 🖥 Backend: 🎤 VOICE PIPELINE: converse request"
echo "8. 🖥 Backend: 🎤 VOICE PIPELINE: converse response"
echo "9. 📥 API RESPONSE: reply='I can hear you...'"
echo "10. 🔊 SPEAKING: Response will be spoken"
echo ""

echo "🎯 Debugging Commands:"
echo "Xcode Console Filter: 🎤 VOICE PIPELINE OR 🏁 VOICE COMPLETE"
echo "Backend Terminal Filter: 🎤 VOICE PIPELINE"
echo ""
echo "🚀 Now test your voice pipeline and watch for complete flow!"
