import { OpportunitiesService } from './opportunities.service';
import { CreateOpportunityDto } from './dto/create-opportunity.dto';
import { UpdateOpportunityDto } from './dto/update-opportunity.dto';
export declare class OpportunitiesController {
    private readonly opportunitiesService;
    constructor(opportunitiesService: OpportunitiesService);
    create(createOpportunityDto: CreateOpportunityDto, req: any): Promise<{
        id: string;
        userId: string;
        companyId: string;
        primaryPersonId: string | null;
        title: string;
        opportunityType: import("@opportunity-os/db").$Enums.OpportunityType;
        stage: import("@opportunity-os/db").$Enums.OpportunityStage;
        status: string | null;
        source: string | null;
        priority: string | null;
        fitScore: number | null;
        qualificationScore: number | null;
        summary: string | null;
        nextAction: string | null;
        nextActionDate: Date | null;
        estimatedValueCents: number | null;
        closeProbability: number | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findAll(req: any): Promise<{
        id: string;
        userId: string;
        companyId: string;
        primaryPersonId: string | null;
        title: string;
        opportunityType: import("@opportunity-os/db").$Enums.OpportunityType;
        stage: import("@opportunity-os/db").$Enums.OpportunityStage;
        status: string | null;
        source: string | null;
        priority: string | null;
        fitScore: number | null;
        qualificationScore: number | null;
        summary: string | null;
        nextAction: string | null;
        nextActionDate: Date | null;
        estimatedValueCents: number | null;
        closeProbability: number | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    findOne(id: string, req: any): Promise<{
        id: string;
        userId: string;
        companyId: string;
        primaryPersonId: string | null;
        title: string;
        opportunityType: import("@opportunity-os/db").$Enums.OpportunityType;
        stage: import("@opportunity-os/db").$Enums.OpportunityStage;
        status: string | null;
        source: string | null;
        priority: string | null;
        fitScore: number | null;
        qualificationScore: number | null;
        summary: string | null;
        nextAction: string | null;
        nextActionDate: Date | null;
        estimatedValueCents: number | null;
        closeProbability: number | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    update(id: string, updateOpportunityDto: UpdateOpportunityDto, req: any): Promise<{
        id: string;
        userId: string;
        companyId: string;
        primaryPersonId: string | null;
        title: string;
        opportunityType: import("@opportunity-os/db").$Enums.OpportunityType;
        stage: import("@opportunity-os/db").$Enums.OpportunityStage;
        status: string | null;
        source: string | null;
        priority: string | null;
        fitScore: number | null;
        qualificationScore: number | null;
        summary: string | null;
        nextAction: string | null;
        nextActionDate: Date | null;
        estimatedValueCents: number | null;
        closeProbability: number | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    remove(id: string, req: any): Promise<void>;
}
//# sourceMappingURL=opportunities.controller.d.ts.map